image: python:3.8

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  key:
    files:
      - requirements.txt
      - gitlab-ci.yml
    prefix: ${CI_JOB_NAME}
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python3.9 --version  # For debugging
  - python3.9 -m venv ./venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt
  - pip3 install dvc[gdrive]

type_test:
  script:
    - pip3 install mypy
    - pip3 install types-six
    - mypy --ignore-missing-imports main.py

unit_test:
  script:
    - dvc pull
    - dvc repro
    - python -m unittest discover tests